### ISSUE TITLE
compilation failing for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by crossi704** [cesarb/clear_on_drop#21] opened 2019-08-14 14:48 UTC
```
__error: failed to run custom build command for `clear_on_drop v0.2.3`

Caused by:
  process didn't exit successfully: `/home/crossi/workspace/myProject/target/debug/build/clear_on_drop-680c14ee5dccb3ea/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("wasm32-unknown-unknown")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-o" "/home/crossi/workspace/wasm-game-of-life/target/wasm32-unknown-unknown/debug/build/clear_on_drop-8ec7b1d55133880a/out/src/hide.o" "-c" "src/hide.c"
cargo:warning=error: unable to create target: 'No available targets are compatible with this triple.'
cargo:warning=1 error generated.
exit code: 1

```
--- stderr

_error occurred: Command "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-o" "/home/crossi/workspace/myProject/target/wasm32-unknown-unknown/debug/build/clear_on_drop-8ec7b1d55133880a/out/src/hide.o" "-c" "src/hide.c" with args "clang" did not execute successfully (status code exit code: 1)_

stable-x86_64-unknown-linux-gnu unchanged - rustc 1.36.0 (a53f9df32 2019-07-03)
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.38.0-nightly (60960a260 2019-08-12)__

Tried with both channels (stable and nightly) and got the same error.

**Comment by cesarb** [comment] 2019-08-20 23:15
According to the error message, the issue is that your C compiler (in this case, `clang`) does not know the `wasm32-unknown-unknown` target. That is not something which could be fixed by this crate.

**Closed as completed** 2019-08-21 09:41 UTC
